openapi: 3.0.3
info:
  title: Nowhere Land Blog API - Admin Settings Domain
  description: Administrative configuration and site management
  version: 1.0.0
  contact:
    name: Kyojun Jin
    email: jan@nowhereland.com

servers:
  - url: https://your-project.supabase.co
    description: Supabase production server
  - url: https://your-dev-project.supabase.co
    description: Supabase development server

security:
  - JWTAuth: []

paths:
  # =================================================================
  # SITE SETTINGS (PostgREST)
  # =================================================================
  /rest/v1/site_setting:
    get:
      tags: [Site Settings]
      summary: Get site settings (Admin only)
      description: Retrieve all site configuration settings
      responses:
        '200':
          description: List of site settings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './nowhereland-api-components.yaml#/components/schemas/SiteSetting'
        '401':
          $ref: './nowhereland-api-components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './nowhereland-api-components.yaml#/components/responses/ForbiddenError'

    patch:
      tags: [Site Settings]
      summary: Update site setting (Admin only)
      description: Update a specific site configuration setting
      parameters:
        - name: key
          in: query
          required: true
          schema:
            type: string
          description: Setting key to update
          example: "site_title"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [value]
              properties:
                value:
                  type: string
                  description: New setting value
              example:
                value: "Nowhere Land - Personal Blog"
      responses:
        '200':
          description: Site setting updated successfully
          content:
            application/json:
              schema:
                $ref: './nowhereland-api-components.yaml#/components/schemas/SuccessResponse'
        '400':
          $ref: './nowhereland-api-components.yaml#/components/responses/ValidationError'
        '401':
          $ref: './nowhereland-api-components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './nowhereland-api-components.yaml#/components/responses/ForbiddenError'
        '404':
          $ref: './nowhereland-api-components.yaml#/components/responses/NotFoundError'

  # =================================================================
  # ABOUT ME MANAGEMENT (PostgREST for read, Edge Function for atomic updates)
  # =================================================================
  /rest/v1/about_me:
    get:
      tags: [About Me]
      summary: Get about me content
      description: Retrieve about me page content
      security: []
      responses:
        '200':
          description: About me content
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    user_id:
                      type: string
                    content:
                      type: string
                      description: About me content in markdown
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time

  /rest/v1/contact:
    get:
      tags: [About Me]
      summary: Get active contacts
      description: Retrieve active contact information for display
      security: []
      parameters:
        - $ref: './nowhereland-api-components.yaml#/components/parameters/IsActiveParam'
        - $ref: './nowhereland-api-components.yaml#/components/parameters/IsDeletedParam'
        - name: order
          in: query
          schema:
            type: string
          example: "sort_order.asc"
          description: Sort order for contacts
      responses:
        '200':
          description: List of active contacts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './nowhereland-api-components.yaml#/components/schemas/Contact'

  # Atomic update via Edge Function
  /functions/v1/about-me:
    post:
      tags: [About Me]
      summary: Update about me content and contacts atomically (Admin only)
      description: Update about me page content and contact information in a single transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [content]
              properties:
                content:
                  type: string
                  description: About me content in markdown
                contacts:
                  type: array
                  description: Contact information array
                  items:
                    type: object
                    required: [type, url]
                    properties:
                      type:
                        type: string
                        enum: [email, x, instagram, facebook, phone]
                        description: Contact type
                      display_name:
                        type: string
                        maxLength: 100
                        description: Display name for contact
                      url:
                        type: string
                        description: Contact URL or value
                      is_active:
                        type: boolean
                        default: true
                        description: Whether contact is visible
                      sort_order:
                        type: integer
                        default: 0
                        description: Display order (ascending)
              example:
                content: "# About Me\n\nI'm a software developer passionate about web technologies..."
                contacts:
                  - type: "email"
                    display_name: "Email"
                    url: "jan@nowhereland.com"
                    is_active: true
                    sort_order: 1
                  - type: "x"
                    display_name: "Twitter"
                    url: "https://x.com/username"
                    is_active: true
                    sort_order: 2
      responses:
        '200':
          description: About me updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  content_updated:
                    type: boolean
                  contacts_updated:
                    type: integer
                    description: Number of contacts updated
                  message:
                    type: string
        '400':
          $ref: './nowhereland-api-components.yaml#/components/responses/ValidationError'
        '401':
          $ref: './nowhereland-api-components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './nowhereland-api-components.yaml#/components/responses/ForbiddenError'

components:
  securitySchemes:
    JWTAuth:
      $ref: './nowhereland-api-components.yaml#/components/securitySchemes/JWTAuth'

  schemas:
    SiteSetting:
      $ref: './nowhereland-api-components.yaml#/components/schemas/SiteSetting'
    
    Contact:
      $ref: './nowhereland-api-components.yaml#/components/schemas/Contact'
    
    AdminNotification:
      $ref: './nowhereland-api-components.yaml#/components/schemas/AdminNotification'
    
    ErrorResponse:
      $ref: './nowhereland-api-components.yaml#/components/schemas/ErrorResponse'
    
    SuccessResponse:
      $ref: './nowhereland-api-components.yaml#/components/schemas/SuccessResponse'

tags:
  - name: Site Settings
    description: Site configuration and settings management
  - name: About Me
    description: About me page and contact information management
  - name: Admin Notifications
    description: Admin notification system for moderation and alerts
  - name: Theme Management
    description: Visual theme and styling configuration