openapi: 3.0.3
info:
  title: Nowhere Land Blog API - AI Services Domain
  description: AI-powered content generation and enhancement
  version: 1.0.0
  contact:
    name: Kyojun Jin
    email: jan@nowhereland.com

servers:
  - url: https://your-project.supabase.co
    description: Supabase production server
  - url: https://your-dev-project.supabase.co
    description: Supabase development server

security:
  - JWTAuth: []

paths:
  # =================================================================
  # AI SERVICES (Edge Functions)
  # =================================================================
  /functions/v1/ai-tag-generator:
    post:
      tags: [AI Content Generation]
      summary: Generate tags for post content (Admin only)
      description: Generate relevant tags for blog post using Claude Haiku 3
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, content]
              properties:
                title:
                  type: string
                  maxLength: 255
                  description: Blog post title
                content:
                  type: string
                  description: Blog post content in markdown
                existing_tags:
                  type: array
                  items:
                    type: string
                  maxItems: 10
                  description: Existing tags to consider (optional)
                max_tags:
                  type: integer
                  minimum: 1
                  maximum: 10
                  default: 5
                  description: Maximum number of tags to generate
                include_fixed_tags:
                  type: boolean
                  default: true
                  description: Whether to prioritize fixed tags (dev, beer, personal)
              example:
                title: "Getting Started with Web Development"
                content: "# Introduction\n\nWeb development is the process of building websites..."
                existing_tags: ["tutorial"]
                max_tags: 5
                include_fixed_tags: true
      responses:
        '200':
          description: Tags generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  tags:
                    type: array
                    items:
                      type: string
                    description: Generated tags
                    example: ["dev", "web development", "tutorial", "beginner", "html"]
                  confidence_scores:
                    type: object
                    additionalProperties:
                      type: number
                      minimum: 0
                      maximum: 1
                    description: Confidence score for each tag
                    example:
                      "dev": 0.95
                      "web development": 0.89
                      "tutorial": 0.92
                  processing_time:
                    type: integer
                    description: AI processing time in milliseconds
                    example: 1250
                  model_used:
                    type: string
                    description: AI model used for generation
                    example: "claude-3-haiku-20240307"
                  cost_estimate:
                    type: number
                    description: Estimated cost in USD
                    example: 0.0012
                  warning:
                    type: string
                    nullable: true
                    description: Warning message if any issues occurred
                    example: null
                  error:
                    type: string
                    nullable: true
                    description: Error message if generation failed
                    example: null
        '400':
          description: Invalid input parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "content_too_short"
                  message:
                    type: string
                    example: "Content must be at least 50 characters long"
                  details:
                    type: object
                    properties:
                      min_content_length:
                        type: integer
                        example: 50
                      max_content_length:
                        type: integer
                        example: 50000
        '401':
          $ref: './nowhereland-api-components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './nowhereland-api-components.yaml#/components/responses/ForbiddenError'
        '429':
          description: AI service rate limit exceeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "ai_rate_limit_exceeded"
                  message:
                    type: string
                    example: "Too many AI requests. Please wait before trying again."
                  retry_after:
                    type: integer
                    description: Seconds to wait before retry
                    example: 60
        '503':
          description: AI service temporarily unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "ai_service_unavailable"
                  message:
                    type: string
                    example: "AI service is temporarily unavailable. Please try again later."
                  fallback_available:
                    type: boolean
                    description: Whether fallback generation is available

  /functions/v1/ai-abstract-generator:
    post:
      tags: [AI Content Generation]
      summary: Generate abstract for post content (Admin only)
      description: Generate concise abstract for blog post using Claude Haiku 3
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, content]
              properties:
                title:
                  type: string
                  maxLength: 255
                  description: Blog post title
                content:
                  type: string
                  description: Blog post content in markdown
                target_length:
                  type: integer
                  minimum: 50
                  maximum: 500
                  default: 150
                  description: Target abstract length in characters
                style:
                  type: string
                  enum: [academic, casual, technical, blog]
                  default: blog
                  description: Writing style for the abstract
                include_keywords:
                  type: array
                  items:
                    type: string
                  maxItems: 5
                  description: Keywords to include in abstract
              example:
                title: "Getting Started with Web Development"
                content: "# Introduction\n\nWeb development is the process of building websites..."
                target_length: 150
                style: "blog"
                include_keywords: ["beginner", "tutorial"]
      responses:
        '200':
          description: Abstract generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  abstract:
                    type: string
                    description: Generated abstract
                    example: "A comprehensive guide for beginners looking to start their web development journey. This tutorial covers the fundamentals of building websites using HTML, CSS, and JavaScript."
                  word_count:
                    type: integer
                    description: Number of words in generated abstract
                    example: 28
                  character_count:
                    type: integer
                    description: Number of characters in generated abstract
                    example: 168
                  readability_score:
                    type: number
                    description: Flesch reading ease score
                    example: 65.2
                  keywords_included:
                    type: array
                    items:
                      type: string
                    description: Requested keywords that were included
                    example: ["beginner", "tutorial"]
                  processing_time:
                    type: integer
                    description: AI processing time in milliseconds
                    example: 1850
                  model_used:
                    type: string
                    description: AI model used for generation
                    example: "claude-3-haiku-20240307"
                  cost_estimate:
                    type: number
                    description: Estimated cost in USD
                    example: 0.0018
                  alternative_versions:
                    type: array
                    items:
                      type: string
                    maxItems: 2
                    description: Alternative abstract versions
                    example: [
                      "Learn web development from scratch with this beginner-friendly tutorial covering HTML, CSS, and JavaScript fundamentals.",
                      "Start your web development career with this comprehensive guide that teaches essential skills for building modern websites."
                    ]
                  warning:
                    type: string
                    nullable: true
                    description: Warning message if any issues occurred
                    example: null
                  error:
                    type: string
                    nullable: true
                    description: Error message if generation failed
                    example: null
        '400':
          description: Invalid input parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "content_too_short"
                  message:
                    type: string
                    example: "Content must be at least 100 characters long for abstract generation"
                  details:
                    type: object
                    properties:
                      min_content_length:
                        type: integer
                        example: 100
                      max_content_length:
                        type: integer
                        example: 50000
                      target_length_range:
                        type: object
                        properties:
                          min:
                            type: integer
                            example: 50
                          max:
                            type: integer
                            example: 500
        '401':
          $ref: './nowhereland-api-components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './nowhereland-api-components.yaml#/components/responses/ForbiddenError'
        '429':
          description: AI service rate limit exceeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "ai_rate_limit_exceeded"
                  message:
                    type: string
                    example: "Too many AI requests. Please wait before trying again."
                  retry_after:
                    type: integer
                    description: Seconds to wait before retry
                    example: 60
                  daily_quota_used:
                    type: number
                    description: Percentage of daily AI quota used
                    example: 85.2
        '503':
          description: AI service temporarily unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "ai_service_unavailable"
                  message:
                    type: string
                    example: "AI service is temporarily unavailable. Please try again later."
                  fallback_available:
                    type: boolean
                    description: Whether fallback generation is available

components:
  securitySchemes:
    JWTAuth:
      $ref: './nowhereland-api-components.yaml#/components/securitySchemes/JWTAuth'

  schemas:
    ErrorResponse:
      $ref: './nowhereland-api-components.yaml#/components/schemas/ErrorResponse'
    
    SuccessResponse:
      $ref: './nowhereland-api-components.yaml#/components/schemas/SuccessResponse'

tags:
  - name: AI Content Generation
    description: AI-powered tag and abstract generation
  - name: AI Service Management
    description: AI service configuration and monitoring (Admin only)